### ISSUE TITLE
从2.04开始，就出现连接不上Aria2的问题

### ISSUE THREAD

**Issue by lvleitading** [aiqinxuancai/Aria2Fast#1]
从2.04开始，到最新的2.05，都会出现无法连接Aria2的问题，无论是用本地的还是远程的
![无标题](https://github.com/aiqinxuancai/Aria2Fast/assets/62314790/8a394c5e-51e4-48ff-b8aa-7f9fc78092f4)

**Comment by aiqinxuancai** [comment]
请检查一下，压缩包的文件是否完全解压，Aria2Fast/Aria2/aria2c.exe是否存在

**Comment by lvleitading** [comment]
> 请检查一下，压缩包的文件是否完全解压，Aria2Fast/Aria2/aria2c.exe是否存在

都有的，我试过几台电脑都这样，而且用远程RPC也是这样。用回2.03一切正常

**Comment by aiqinxuancai** [comment]
> > 请检查一下，压缩包的文件是否完全解压，Aria2Fast/Aria2/aria2c.exe是否存在
> 
> 都有的，我试过几台电脑都这样，而且用远程RPC也是这样。用回2.03一切正常

是个bug，我稍后修复发布2.0.6

**Comment by aiqinxuancai** [comment]
https://github.com/aiqinxuancai/Aria2Fast/tree/v2.0.6 
修复了
